import { AllowNull, BelongsTo, Column, DataType, ForeignKey, IsUUID, Model, PrimaryKey, Table } from 'sequelize-typescript';
import { UserModel } from 'src/users/user.model';

// createdAt and updatedAt generated by default unless used @Table({timestamps: false})

@Table({ modelName: 'Photo', paranoid: true })
export class PhotoModel extends Model {
  @IsUUID('4')
  @AllowNull(false)
  @PrimaryKey
  @Column(DataType.UUID)
  id: string;

  @Column
  title: string;

  @Column
  meta: string;

  @ForeignKey(() => UserModel)
  @Column(DataType.UUID)
  userId: string;

  // 'BelongsTo' method will just allow source table i.e. PhotoModel to join UserModel
  @BelongsTo(() => UserModel, 'userId')
  user: UserModel;
}
